### ISSUE TITLE
Error: No named parameter with the name 'replaceMovedChildren'.

### ISSUE THREAD

**Issue by dcbacarro** [pstromberg98/flutter_bouncy#1]
I tried to install this package and use the example code. But the app fails to build and returns the following:

../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_bouncy-1.0.0/lib/src/sliver_bouncy_list.dart:24:42: Error: No named parameter with the name 'replaceMovedChildren'.
      SliverMultiBoxAdaptorElement(this, replaceMovedChildren: true);
                                         ^^^^^^^^^^^^^^^^^^^^

../flutter/packages/flutter/lib/src/widgets/sliver.dart:1039:3: Context: Found this candidate, but the arguments don't match.
SliverMultiBoxAdaptorElement(SliverMultiBoxAdaptorWidget widget) : super(widget);
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3

FAILURE: Build failed with an exception.

Please help

**Comment by pstromberg98** [comment]
@dcbacarro What is your `flutter doctor -v` output?

**Comment by pstromberg98** [comment]
@dcbacarro I just published a fix for you under version 1.0.1

**Comment by dcbacarro** [comment]
Thank you very much, @pstromberg98!
