### ISSUE TITLE
childParentData.index == index assertion fails on scrolling to last item and Null Safety support please

### ISSUE THREAD

**Issue by ashishbeck** [pstromberg98/flutter_bouncy#10]
I know there are already three more threads for null safety requests but can we please have a working null safe update?

I tried to make it null safe but it is still not perfect. Especially when I scroll to the last item in my list, the assertion `childParentData.index == index` fails and the frames drop to 5fps.

**Comment by pstromberg98** [comment]
https://github.com/pstromberg98/flutter_bouncy/issues/12
