### ISSUE TITLE
Does it works with flutter_staggered_grid_view ?

### ISSUE THREAD

**Issue by sooxt98** [pstromberg98/flutter_bouncy#5]

**Comment by vaibhav891** [comment]
@sooxt98 Were you able to make it work with flutter_staggered_grid_view? Did you find any solution for this? I too am looking for something similar.

**Comment by pstromberg98** [comment]
Sorry for the late reply, other things have been keeping me very busy. Support for a bouncy grid view is definitely something that I want the library to have. I am going to be starting work on this project again and there is a refactor that needs to be done before I add any extra features. But this will be soon after that refactor for sure!
